project:
  type: website
  output-dir: docs

website:
  title: "Learning Packer - Themes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: a.qmd
        text: A

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
